export const US_STOCK_NAMES: Record<string, string> = {
  AAPL: '애플',
  MSFT: '마이크로소프트',
  GOOGL: '알파벳 A',
  GOOG: '알파벳 C',
  AMZN: '아마존',
  META: '메타',
  NVDA: '엔비디아',
  TSLA: '테슬라',
  NFLX: '넷플릭스',
  ORCL: '오라클',
  AMD: 'AMD',
  INTC: '인텔',
  QCOM: '퀄컴',
  AVGO: '브로드컴',
  TXN: '텍사스인스트루먼츠',
  IBM: 'IBM',
  CSCO: '시스코',
  CRM: '세일즈포스',
  ADBE: '어도비',
  NOW: '서비스나우',
  UBER: '우버',
  LYFT: '리프트',
  ABNB: '에어비앤비',
  DASH: '도어대시',
  COIN: '코인베이스',
  HOOD: '로빈후드',
  PLTR: '팔란티어',
  SNOW: '스노우플레이크',
  NET: '클라우드플레어',
  DDOG: '데이터독',
  ZS: '지스케일러',
  CRWD: '크라우드스트라이크',
  PANW: '팔로알토네트웍스',
  FTNT: '포티넷',
  MDB: '몽고DB',
  HIMS: '힘스앤허스',
  SPOT: '스포티파이',
  PINS: '핀터레스트',
  SNAP: '스냅',
  TWTR: '트위터',
  DIS: '디즈니',
  CMCSA: '컴캐스트',
  T: 'AT&T',
  VZ: '버라이즌',
  JPM: 'JP모건',
  BAC: '뱅크오브아메리카',
  WFC: '웰스파고',
  GS: '골드만삭스',
  MS: '모건스탠리',
  BLK: '블랙록',
  V: '비자',
  MA: '마스터카드',
  PYPL: '페이팔',
  SQ: '블록(스퀘어)',
  AXP: '아메리칸익스프레스',
  BRK: '버크셔해서웨이',
  'BRK.B': '버크셔해서웨이 B',
  'BRK.A': '버크셔해서웨이 A',
  JNJ: '존슨앤존슨',
  PFE: '화이자',
  MRNA: '모더나',
  ABBV: '애브비',
  LLY: '일라이릴리',
  UNH: '유나이티드헬스',
  CVS: 'CVS헬스',
  WMT: '월마트',
  TGT: '타겟',
  COST: '코스트코',
  AMGN: '암젠',
  GILD: '길리어드',
  XOM: '엑슨모빌',
  CVX: '셰브론',
  BA: '보잉',
  CAT: '캐터필러',
  GE: 'GE에어로스페이스',
  HON: '하니웰',
  MMM: '3M',
  SBUX: '스타벅스',
  MCD: '맥도날드',
  NKE: '나이키',
  PG: 'P&G',
  KO: '코카콜라',
  PEP: '펩시코',
  PM: '필립모리스',
  BABA: '알리바바',
  JD: '징둥닷컴',
  BIDU: '바이두',
  NIO: '니오',
  XPEV: '샤오펑',
  LI: '리오토모빌',
  TSM: 'TSMC',
  ASML: 'ASML',
  SAP: 'SAP',
  TM: '도요타',
  SONY: '소니',
  ARM: 'ARM홀딩스',
  SPCX: '스페이스X',
  MSTR: '마이크로스트래티지',
  APP: '앱러빈',
  CELH: '셀시어스홀딩스',
  RBLX: '로블록스',
  DOCS: '도시스피크',
  U: '유니티소프트웨어',
  AFRM: '어펌',
  SOFI: '소파이',
  RIVN: '리비안',
  LCID: '루시드모터스',
  CHWY: '츄이',
  ETSY: '엣시',
  EBAY: '이베이',
  SHOP: '쇼피파이',
  TTD: '더트레이드데스크',
  ROKU: '로쿠',
  ZM: '줌비디오',
  DOCU: '도큐사인',
  TWLO: '트윌리오',
  OKTA: '옥타',
  BILL: '빌닷컴',
  HCP: '해시코프',
  PATH: 'UiPath',
  AI: 'C3.ai',
  IONQ: '아이온큐',
  RGTI: '리게티컴퓨팅',
  QBTS: 'D-Wave퀀텀',
  C: '씨티그룹',
  USB: 'US뱅코프',
  PNC: 'PNC파이낸셜',
  SCHW: '찰스슈왑',
  COF: '캐피탈원',
  DFS: '디스커버파이낸셜',
  ICE: '인터콘티넨탈익스체인지',
  CME: 'CME그룹',
  SPGI: 'S&P글로벌',
  MCO: '무디스',
  BMY: '브리스톨마이어스스큅',
  MRK: '머크',
  BIIB: '바이오젠',
  REGN: '리제네론',
  VRTX: '버텍스파마슈티컬스',
  ISRG: '인튜이티브서지컬',
  BSX: '보스턴사이언티픽',
  MDT: '메드트로닉',
  ABT: '애보트',
  TMO: '써모피셔사이언티픽',
  DHR: '다나허',
  HD: '홈디포',
  LOW: '로우스',
  TJX: 'TJX컴퍼니즈',
  BKNG: '부킹홀딩스',
  EXPE: '익스피디아',
  MAR: '메리어트',
  HLT: '힐튼',
  YUM: 'YUM브랜즈',
  CMG: '치폴레',
  DKNG: '드래프트킹스',
  COP: '코노코필립스',
  SLB: '슐럼버거',
  EOG: 'EOG리소시스',
  NEE: '넥스트에라에너지',
  DUK: '듀크에너지',
  SO: '서던컴퍼니',
  LIN: '린데',
  APD: '에어프로덕츠',
  RTX: '레이시온테크놀로지스',
  LMT: '록히드마틴',
  NOC: '노스럽그러먼',
  DE: '존디어',
  UPS: 'UPS',
  FDX: '페덱스',
  AMT: '아메리칸타워',
  PLD: '프로로지스',
  EQIX: '에퀴닉스',
  CCI: '크라운캐슬',
  O: '리얼티인컴',
  SPG: '사이먼프로퍼티그룹',
  HSBA: 'HSBC',
  BP: 'BP',
  SHEL: '쉘',
  RIO: '리오틴토',
  BHP: 'BHP그룹',
  NVO: '노보노디스크',
  LVMH: 'LVMH',
  MC: 'LVMH(파리)',
  SIE: '지멘스',
  BNTX: '바이오엔텍',
  SE: '씨(그랩)',
  GRAB: '그랩홀딩스',
  MELI: '메르카도리브레',
  NU: '누홀딩스',
  PDD: '핀둬둬(테무)',
  BILI: '빌리빌리',
  TCEHY: '텐센트',
  KWEB: '차이나인터넷',

  // 반도체
  MU: '마이크론테크놀로지',
  MRVL: '마벨테크놀로지',
  AMAT: '어플라이드머티리얼즈',
  LRCX: '램리서치',
  KLAC: 'KLA',
  NXPI: 'NXP반도체',
  MCHP: '마이크로칩테크놀로지',
  ON: 'ON반도체',
  MPWR: '모놀리식파워시스템즈',
  SMCI: '슈퍼마이크로컴퓨터',
  GFS: '글로벌파운드리즈',
  WOLF: '울프스피드',
  ENTG: '엔테그리스',

  // 소프트웨어/IT
  INTU: '인튜이트',
  ADSK: '오토데스크',
  ACN: '액센츄어',
  CDNS: '케이던스디자인',
  SNPS: '시놉시스',
  FICO: 'FICO',
  ANSS: 'ANSYS',
  ROP: '로퍼테크놀로지스',
  VRSK: '베리스크애널리틱스',
  GOOG2: '알파벳',
  WIT: '위프로',
  INFY: '인포시스',
  IT: '가트너',

  // 헬스케어/바이오
  SYK: '스트라이커',
  EW: '에드워즈라이프사이언시즈',
  DXCM: '덱스콤',
  IDXX: 'IDEXX래버러토리즈',
  IQV: 'IQVIA홀딩스',
  ZTS: '조에티스',
  A: '애질런트테크놀로지스',
  ELV: '엘레반스헬스',
  CI: '시그나',
  HUM: '휴마나',
  MCK: '맥케슨',
  ZBH: '짐머바이오멧',
  HOLX: '홀로직',
  ILMN: '일루미나',

  // 금융
  FI: '피서브',
  FIS: '피델리티내셔널정보서비스',
  GPN: '글로벌페이먼츠',
  ALLY: '앨라이파이낸셜',
  CBOE: 'CBOE글로벌마켓',
  NDAQ: '나스닥',
  AMP: '아메리프라이즈파이낸셜',
  TROW: 'T로우프라이스',
  BEN: '프랭클린리소시즈',
  STT: '스테이트스트리트',
  KEY: '키코프',
  RF: '리전스파이낸셜',
  FITB: '피프스서드뱅코프',
  HBAN: '헌팅턴뱅크셰어스',

  // 소비재/리테일
  LULU: '룰루레몬',
  ONON: '온홀딩',
  DECK: '데커스',
  ULTA: '울타뷰티',
  MNST: '몬스터비버리지',
  MDLZ: '몬델리즈',
  KHC: '크래프트하인즈',
  CL: '콜게이트팜올리브',
  KO2: '코카콜라',
  STZ: '컨스텔레이션브랜즈',
  MO: '알트리아',
  GIS: '제너럴밀스',
  HSY: '허쉬',
  SYY: '시스코(식품유통)',
  F: '포드',
  GM: '제너럴모터스',
  STLA: '스텔란티스',

  // 산업재
  ETN: '이튼',
  EMR: '에머슨일렉트릭',
  PH: '파커하니핀',
  ROK: '로크웰오토메이션',
  IR: '잉거솔랜드',
  TT: '트레인테크놀로지스',
  CARR: '캐리어글로벌',
  OTIS: '오티스월드와이드',
  WM: '웨이스트매니지먼트',
  RSG: '리퍼블릭서비시즈',
  CTAS: '신타스',
  FAST: '패스트널',
  GWW: 'W.W.그레인저',

  // 에너지/소재
  FCX: '프리포트맥모란',
  NEM: '뉴몬트',
  ALB: '알베말',
  ENPH: '엔페이즈에너지',
  FSLR: '퍼스트솔라',
  OXY: '옥시덴탈페트롤리엄',

  // 리츠
  WELL: '웰타워',
  DLR: '디지털리얼티',
  PSA: '퍼블릭스토리지',
  EXR: '엑스트라스페이스스토리지',
  AVB: '어벌론베이커뮤니티즈',

  // 크립토 관련
  MARA: '마라톤디지털',
  RIOT: '라이엇플랫폼즈',
  CLSK: '클린스파크',
  UPST: '업스타트',
}

export const US_ETF_NAMES: Record<string, string> = {
  SPY: 'S&P500 ETF',
  VOO: 'S&P500 ETF',
  IVV: 'S&P500 ETF',
  QQQ: '나스닥100 ETF',
  QQQM: '나스닥100 ETF',
  VTI: '미국전체시장 ETF',
  VT: '전세계주식 ETF',
  SCHD: '배당 ETF',
  VYM: '고배당 ETF',
  JEPI: '커버드콜배당 ETF',
  JEPQ: '나스닥커버드콜 ETF',
  QLD: '나스닥100 2배 ETF',
  TQQQ: '나스닥3배 ETF',
  SOXL: '반도체3배 ETF',
  SOXX: '반도체 ETF',
  SMH: '반도체 ETF',
  ARKK: '아크이노베이션 ETF',
  GLD: '금 ETF',
  IAU: '금 ETF',
  SLV: '은 ETF',
  USO: '원유 ETF',
  TLT: '미국장기채 ETF',
  IEF: '미국중기채 ETF',
  HYG: '하이일드채권 ETF',
  LQD: '투자등급채권 ETF',
  VNQ: '리츠 ETF',
  IBIT: '비트코인 ETF (블랙록)',
  FBTC: '비트코인 ETF (피델리티)',
  SPYG: 'S&P500 성장주 ETF',
  SPYV: 'S&P500 가치주 ETF',
  VUG: '미국대형성장 ETF',
  VTV: '미국대형가치 ETF',
  VO: '미국중형주 ETF',
  VB: '미국소형주 ETF',
  IWM: '러셀2000 ETF',
  IWF: '러셀1000성장 ETF',
  DIA: '다우존스 ETF',
  RSP: 'S&P500동일비중 ETF',
  SPLG: 'S&P500 ETF',
  CSPX: 'S&P500 ETF (iShares)',
  VGT: '미국IT섹터 ETF',
  XLK: '테크섹터 ETF',
  XLF: '금융섹터 ETF',
  XLE: '에너지섹터 ETF',
  XLV: '헬스케어섹터 ETF',
  XLI: '산업섹터 ETF',
  XLP: '필수소비재섹터 ETF',
  XLY: '임의소비재섹터 ETF',
  XLU: '유틸리티섹터 ETF',
  XLRE: '부동산섹터 ETF',
  XLB: '소재섹터 ETF',
  XLC: '커뮤니케이션섹터 ETF',
  ARKQ: '아크자율기술로봇 ETF',
  ARKG: '아크게놈혁명 ETF',
  ARKW: '아크인터넷 ETF',
  ARKF: '아크핀테크 ETF',
  BOTZ: '글로벌로보틱스AI ETF',
  ROBO: '로보틱스자동화 ETF',
  AIQ: 'AI빅데이터 ETF',
  CLOU: '클라우드컴퓨팅 ETF',
  WCLD: '위즈덤트리클라우드 ETF',
  SKYY: '클라우드컴퓨팅 ETF',
  HACK: '사이버보안 ETF',
  BUG: '글로벌사이버보안 ETF',
  CIBR: '사이버보안 ETF',
  FINX: '핀테크 ETF',
  BLOK: '블록체인 ETF',
  BITO: '비트코인선물 ETF',
  GBTC: '그레이스케일비트코인',
  ETHA: '이더리움 ETF (블랙록)',
  FETH: '이더리움 ETF (피델리티)',
  MCHI: '중국주식 ETF',
  FXI: '중국대형주 ETF',
  EEM: '신흥국 ETF',
  VWO: '신흥국 ETF (뱅가드)',
  EFA: '선진국(미국제외) ETF',
  IEFA: '선진국(미국제외) ETF (iShares)',
  EWJ: '일본주식 ETF',
  EWY: '한국주식 ETF',
  EWT: '대만주식 ETF',
  EWG: '독일주식 ETF',
  EWU: '영국주식 ETF',
  EWQ: '프랑스주식 ETF',
  INDA: '인도주식 ETF',
  INDY: '인도대형주 ETF',
  VEA: '선진국주식 ETF',
  AGG: '미국채권종합 ETF',
  BND: '미국채권 ETF (뱅가드)',
  SHY: '미국단기채 ETF',
  SGOV: '미국초단기국채 ETF',
  TIPS: '미국물가연동채 ETF',
  EMB: '신흥국채권 ETF',
  BNDX: '해외채권 ETF',
  SPAB: 'S&P미국채권 ETF',
  PDBC: '원자재 ETF',
  DBC: '원자재지수 ETF',
  PDBA: '농산물 ETF',
  UCO: '원유2배 ETF',
  SCO: '원유인버스 ETF',
  GLDM: '금 ETF',
  SGOL: '금 ETF (애버딘)',
  PPLT: '백금 ETF',
  PALL: '팔라듐 ETF',
  UNG: '천연가스 ETF',
  DBO: '원유선물 ETF',
  SSO: 'S&P500 2배 ETF',
  UPRO: 'S&P500 3배 ETF',
  SPXU: 'S&P500 인버스3배 ETF',
  SH: 'S&P500 인버스 ETF',
  SQQQ: '나스닥100 인버스3배 ETF',
  PSQ: '나스닥100 인버스 ETF',
  SPXS: 'S&P500 3배인버스 ETF',
  UVXY: 'VIX 1.5배 ETF',
  VXX: 'VIX 단기선물 ETF',
  SVXY: 'VIX 인버스 ETF',
  SOXS: '반도체 인버스3배 ETF',
  LABU: '바이오 3배 ETF',
  LABD: '바이오 인버스3배 ETF',
  FAS: '금융 3배 ETF',
  FAZ: '금융 인버스3배 ETF',
  TNA: '러셀2000 3배 ETF',
  MSFO: '마이크로소프트커버드콜 ETF',
  NVDL: '엔비디아 2배 ETF',
  TSLL: '테슬라 2배 ETF',
  MSTU: '마이크로스트래티지 2배 ETF',
  YMAX: '옵션인컴 ETF',
  YMAG: '매그니피센트7커버드콜 ETF',
  FEPI: '테크커버드콜배당 ETF',
  ULTY: '고배당커버드콜 ETF',
  MSTY: '마이크로스트래티지커버드콜 ETF',
  CONY: '코인베이스커버드콜 ETF',
  NVDY: '엔비디아커버드콜 ETF',
  TSLY: '테슬라커버드콜 ETF',
  AMZY: '아마존커버드콜 ETF',
  GOOGY: '알파벳커버드콜 ETF',
  APLY: '애플커버드콜 ETF',
  MSFO2: '마이크로소프트커버드콜 ETF2',
  DIVO: '액티브배당성장 ETF',
  DGRO: '배당성장 ETF (블랙록)',
  VIG: '배당성장 ETF (뱅가드)',
  HDV: '고배당 ETF (블랙록)',
  DVY: '다우고배당 ETF',
  SDY: 'S&P배당귀족 ETF',
  NOBL: 'S&P배당귀족 ETF (ProShares)',
  SPHD: 'S&P500고배당저변동 ETF',
  NUSI: '나스닥소득 ETF',
}
