/**
 * 티커 → 한글명 매핑 테이블
 * 없는 종목은 티커를 그대로 표시
 */
export const TICKER_NAMES: Record<string, string> = {
  // ── 현금 ───────────────────────────────────────
  CASH: '보유현금',
  CASH_KRW: '원화현금',
  CASH_USD: '달러현금',

  // ── 미국 주식 ──────────────────────────────────
  AAPL: '애플',
  MSFT: '마이크로소프트',
  GOOGL: '알파벳 A',
  GOOG: '알파벳 C',
  AMZN: '아마존',
  META: '메타',
  NVDA: '엔비디아',
  TSLA: '테슬라',
  NFLX: '넷플릭스',
  ORCL: '오라클',
  AMD: 'AMD',
  INTC: '인텔',
  QCOM: '퀄컴',
  AVGO: '브로드컴',
  TXN: '텍사스인스트루먼츠',
  IBM: 'IBM',
  CSCO: '시스코',
  CRM: '세일즈포스',
  ADBE: '어도비',
  NOW: '서비스나우',
  UBER: '우버',
  LYFT: '리프트',
  ABNB: '에어비앤비',
  DASH: '도어대시',
  COIN: '코인베이스',
  HOOD: '로빈후드',
  PLTR: '팔란티어',
  SNOW: '스노우플레이크',
  NET: '클라우드플레어',
  DDOG: '데이터독',
  ZS: '지스케일러',
  CRWD: '크라우드스트라이크',
  PANW: '팔로알토네트웍스',
  FTNT: '포티넷',
  MDB: '몽고DB',
  HIMS: '힘스앤허스',
  SPOT: '스포티파이',
  PINS: '핀터레스트',
  SNAP: '스냅',
  TWTR: '트위터',
  DIS: '디즈니',
  CMCSA: '컴캐스트',
  T: 'AT&T',
  VZ: '버라이즌',
  JPM: 'JP모건',
  BAC: '뱅크오브아메리카',
  WFC: '웰스파고',
  GS: '골드만삭스',
  MS: '모건스탠리',
  BLK: '블랙록',
  V: '비자',
  MA: '마스터카드',
  PYPL: '페이팔',
  SQ: '블록(스퀘어)',
  AXP: '아메리칸익스프레스',
  BRK: '버크셔해서웨이',
  'BRK.B': '버크셔해서웨이 B',
  JNJ: '존슨앤존슨',
  PFE: '화이자',
  MRNA: '모더나',
  ABBV: '애브비',
  LLY: '일라이릴리',
  UNH: '유나이티드헬스',
  CVS: 'CVS헬스',
  WMT: '월마트',
  TGT: '타겟',
  COST: '코스트코',
  AMGN: '암젠',
  GILD: '길리어드',
  XOM: '엑슨모빌',
  CVX: '셰브론',
  BA: '보잉',
  CAT: '캐터필러',
  GE: 'GE에어로스페이스',
  HON: '하니웰',
  MMM: '3M',
  SBUX: '스타벅스',
  MCD: '맥도날드',
  NKE: '나이키',
  PG: 'P&G',
  KO: '코카콜라',
  PEP: '펩시코',
  PM: '필립모리스',
  BABA: '알리바바',
  JD: '징둥닷컴',
  BIDU: '바이두',
  NIO: '니오',
  XPEV: '샤오펑',
  LI: '리오토모빌',
  TSM: 'TSMC',
  ASML: 'ASML',
  SAP: 'SAP',
  TM: '도요타',
  SONY: '소니',
  ARM: 'ARM홀딩스',
  SPCX: '스페이스X',

  // ── 미국 ETF ───────────────────────────────────
  SPY: 'S&P500 ETF (SPY)',
  VOO: 'S&P500 ETF (VOO)',
  IVV: 'S&P500 ETF (IVV)',
  QQQ: '나스닥100 ETF (QQQ)',
  QQQM: '나스닥100 ETF (QQQM)',
  VTI: '미국전체시장 ETF',
  VT: '전세계주식 ETF',
  SCHD: '배당 ETF (SCHD)',
  VYM: '고배당 ETF (VYM)',
  JEPI: '커버드콜배당 ETF',
  JEPQ: '나스닥커버드콜 ETF',
  QLD: '나스닥100 2배 ETF',
  TQQQ: '나스닥3배 ETF',
  SOXL: '반도체3배 ETF',
  SOXX: '반도체 ETF',
  SMH: '반도체 ETF (SMH)',
  ARKK: '아크이노베이션 ETF',
  GLD: '금 ETF (GLD)',
  IAU: '금 ETF (IAU)',
  SLV: '은 ETF',
  USO: '원유 ETF',
  TLT: '미국장기채 ETF',
  IEF: '미국중기채 ETF',
  HYG: '하이일드채권 ETF',
  LQD: '투자등급채권 ETF',
  VNQ: '리츠 ETF',
  IBIT: '비트코인 ETF (블랙록)',
  FBTC: '비트코인 ETF (피델리티)',

  // ── 국내 주식 ──────────────────────────────────
  '005930': '삼성전자',
  '000660': 'SK하이닉스',
  '035420': 'NAVER',
  '035720': '카카오',
  '005380': '현대차',
  '000270': '기아',
  '068270': '셀트리온',
  '207940': '삼성바이오로직스',
  '005490': 'POSCO홀딩스',
  '028260': '삼성물산',
  '012330': '현대모비스',
  '066570': 'LG전자',
  '003550': 'LG',
  '051910': 'LG화학',
  '006400': '삼성SDI',
  '373220': 'LG에너지솔루션',
  '247540': '에코프로비엠',
  '086520': '에코프로',
  '011200': 'HMM',
  '032830': '삼성생명',
  '055550': '신한지주',
  '105560': 'KB금융',
  '086790': '하나금융지주',
  '316140': '우리금융지주',
  '003490': '대한항공',
  '015760': '한국전력',
  '017670': 'SK텔레콤',
  '030200': 'KT',
  '032640': 'LG유플러스',
  '096770': 'SK이노베이션',
  '034730': 'SK',
  '011170': '롯데케미칼',
  '000100': '유한양행',
  '326030': 'SK바이오팜',
  '263750': '펄어비스',
  '036570': 'NC소프트',
  '251270': '넷마블',
  '112040': '위메이드',
  '259960': '크래프톤',

  // ── 국내 ETF ───────────────────────────────────
  '069500': 'KODEX 200',
  '102110': 'TIGER 200',
  '229200': 'KODEX 코스닥150',
  '133690': 'TIGER 나스닥100',
  '379800': 'KODEX 미국S&P500',
  '360750': 'TIGER 미국S&P500',
  '379810': 'KODEX 미국나스닥100',
  '305720': 'KODEX 2차전지산업',
  '091160': 'KODEX 반도체',
  '278540': 'KODEX 글로벌반도체',
  '148020': 'KOSEF 미국달러선물',
  '272580': 'TIGER 미국채10년선물',
  '498400': 'KODEX 200타겟위클리커버드콜',
  '432080': 'TIGER 미국나스닥100커버드콜',

  // ── 암호화폐 ───────────────────────────────────
  BTC: '비트코인',
  ETH: '이더리움',
  BNB: '바이낸스코인',
  XRP: '리플',
  ADA: '에이다',
  SOL: '솔라나',
  DOGE: '도지코인',
  DOT: '폴카닷',
  MATIC: '폴리곤',
  LINK: '체인링크',
  UNI: '유니스왑',
  AVAX: '아발란체',
  ATOM: '코스모스',
  LTC: '라이트코인',
  BCH: '비트코인캐시',
  NEAR: '니어프로토콜',
  APT: '앱토스',
  ARB: '아비트럼',
  OP: '옵티미즘',
  SUI: '수이',
}

/**
 * 티커로 표시명 반환
 * 매핑에 없으면 ticker 그대로 반환
 */
export const getTickerDisplayName = (ticker: string): string => {
  return TICKER_NAMES[ticker.toUpperCase()] ?? ticker
}

/**
 * 표시명과 티커를 함께 반환 (한글명이 있을 때만 티커 병기)
 */
export const getTickerLabel = (ticker: string): { name: string; showTicker: boolean } => {
  const name = TICKER_NAMES[ticker.toUpperCase()]
  if (name) return { name, showTicker: true }
  return { name: ticker, showTicker: false }
}

/**
 * 티커가 ETF인지 판별 (asset_type 무관하게 이름 기반으로 확인)
 */
export const isEtfTicker = (ticker: string): boolean => {
  const name = TICKER_NAMES[ticker.toUpperCase()]
  return name ? name.includes('ETF') : false
}
